-- ============================================================
-- Permission Table Master Seed — 50-gap, 4-digit IDs
-- PermissionId = SortOrder (always in sync)
-- Primary entity first per module, rest A-Z
-- Actions: View, Create/Edit, Delete first, then specific actions
-- DisplayNames follow cleanup standard
-- ============================================================

DELETE FROM RolePermission;
DELETE FROM Permission;
DBCC CHECKIDENT ('Permission', RESEED, 0);

SET IDENTITY_INSERT Permission ON;

INSERT INTO Permission (PermissionId, PermissionKey, DisplayName, [Module], [Resource], [Action], PermissionType, ParentPermissionId, SortOrder, OldKey) VALUES
(1000, 'Accounting', 'Accounting', 'Accounting', '', '', 'menu', NULL, 1000, NULL),
(1050, 'Accounting.Account', 'Account', 'Accounting', 'Account', '', 'resource', 1000, 1050, NULL),
(1051, 'Accounting.Account.List', 'View Accounts', 'Accounting', 'Account', 'List', 'page', 1050, 1051, 'Accounts-List'),
(1052, 'Accounting.Account.Create', 'Create Account', 'Accounting', 'Account', 'Create', 'button', 1050, 1052, 'Accounts-Create'),
(1053, 'Accounting.Account.Update', 'Edit Account', 'Accounting', 'Account', 'Update', 'button', 1050, 1053, 'Accounts-Update'),
(1054, 'Accounting.Account.Delete', 'Delete Account', 'Accounting', 'Account', 'Delete', 'button', 1050, 1054, 'Accounts-Delete'),
(1100, 'Accounting.BankRecon', 'Bank Reconciliation', 'Accounting', 'BankRecon', '', 'resource', 1000, 1100, NULL),
(1101, 'Accounting.BankRecon.List', 'View Bank Reconciliations', 'Accounting', 'BankRecon', 'List', 'page', 1100, 1101, 'BankRecons-List'),
(1102, 'Accounting.BankRecon.Create', 'Create Reconciliation', 'Accounting', 'BankRecon', 'Create', 'button', 1100, 1102, 'BankRecons-Create'),
(1103, 'Accounting.BankRecon.Update', 'Edit Reconciliation', 'Accounting', 'BankRecon', 'Update', 'button', 1100, 1103, 'BankRecons-Update'),
(1104, 'Accounting.BankRecon.Delete', 'Delete Reconciliation', 'Accounting', 'BankRecon', 'Delete', 'button', 1100, 1104, 'BankRecons-Delete'),
(1150, 'Accounting.CheckRegister', 'Check Register', 'Accounting', 'CheckRegister', '', 'resource', 1000, 1150, NULL),
(1151, 'Accounting.CheckRegister.List', 'View Check Register', 'Accounting', 'CheckRegister', 'List', 'page', 1150, 1151, 'CheckRegister-List'),
(1152, 'Accounting.CheckRegister.Update', 'Edit Check Register', 'Accounting', 'CheckRegister', 'Update', 'button', 1150, 1152, 'CheckRegister-Update'),
(1200, 'Accounting.GeneralJournal', 'General Journal', 'Accounting', 'GeneralJournal', '', 'resource', 1000, 1200, NULL),
(1201, 'Accounting.GeneralJournal.List', 'View General Journals', 'Accounting', 'GeneralJournal', 'List', 'page', 1200, 1201, 'GeneralJournals-List'),
(1202, 'Accounting.GeneralJournal.Save', 'Create or Edit General Journal', 'Accounting', 'GeneralJournal', 'Save', 'button', 1200, 1202, 'GeneralJournals-Save'),
(1203, 'Accounting.GeneralJournal.Delete', 'Delete General Journal', 'Accounting', 'GeneralJournal', 'Delete', 'button', 1200, 1203, 'GeneralJournals-Delete'),
(1250, 'Accounting.IncomingPayment', 'Incoming Payment', 'Accounting', 'IncomingPayment', '', 'resource', 1000, 1250, NULL),
(1251, 'Accounting.IncomingPayment.List', 'View Incoming Payments', 'Accounting', 'IncomingPayment', 'List', 'page', 1250, 1251, 'IncomingPayments-List'),
(1252, 'Accounting.IncomingPayment.Save', 'Create or Edit Incoming Payment', 'Accounting', 'IncomingPayment', 'Save', 'button', 1250, 1252, 'IncomingPayments-Save'),
(1253, 'Accounting.IncomingPayment.Delete', 'Delete Incoming Payment', 'Accounting', 'IncomingPayment', 'Delete', 'button', 1250, 1253, 'IncomingPayments-Delete'),
(1300, 'Accounting.Transaction', 'Transaction', 'Accounting', 'Transaction', '', 'resource', 1000, 1300, NULL),
(1301, 'Accounting.Transaction.List', 'View Transactions', 'Accounting', 'Transaction', 'List', 'page', 1300, 1301, 'Transactions-List'),
(1350, 'Accounting.TransferFund', 'Transfer Fund', 'Accounting', 'TransferFund', '', 'resource', 1000, 1350, NULL),
(1351, 'Accounting.TransferFund.List', 'View Transfer Funds', 'Accounting', 'TransferFund', 'List', 'page', 1350, 1351, 'TransferFunds-List'),
(1352, 'Accounting.TransferFund.Save', 'Create or Edit Transfer Fund', 'Accounting', 'TransferFund', 'Save', 'button', 1350, 1352, 'TransferFunds-Save'),
(1353, 'Accounting.TransferFund.Delete', 'Delete Transfer Fund', 'Accounting', 'TransferFund', 'Delete', 'button', 1350, 1353, 'TransferFunds-Delete'),
(2000, 'Admin', 'Admin', 'Admin', '', '', 'menu', NULL, 2000, NULL),
(2050, 'Admin.Role', 'Role', 'Admin', 'Role', '', 'resource', 2000, 2050, NULL),
(2051, 'Admin.Role.List', 'View Roles', 'Admin', 'Role', 'List', 'page', 2050, 2051, 'Roles-List'),
(2052, 'Admin.Role.Create', 'Create Role', 'Admin', 'Role', 'Create', 'button', 2050, 2052, 'Roles-Create'),
(2053, 'Admin.Role.Update', 'Edit Role', 'Admin', 'Role', 'Update', 'button', 2050, 2053, 'Roles-Update'),
(2054, 'Admin.Role.Delete', 'Delete Role', 'Admin', 'Role', 'Delete', 'button', 2050, 2054, 'Roles-Delete'),
(2055, 'Admin.Role.ViewPermission', 'View Permissions', 'Admin', 'Role', 'ViewPermission', 'button', 2050, 2055, 'Roles-GetControllers'),
(2056, 'Admin.Role.SavePermission', 'Save Permissions', 'Admin', 'Role', 'SavePermission', 'button', 2050, 2056, 'Roles-SavePermission'),
(2100, 'Admin.DocumentTemplate', 'Document Template', 'Admin', 'DocumentTemplate', '', 'resource', 2000, 2100, NULL),
(2101, 'Admin.DocumentTemplate.List', 'View Document Templates', 'Admin', 'DocumentTemplate', 'List', 'page', 2100, 2101, 'DocumentTemplates-List'),
(2102, 'Admin.DocumentTemplate.Create', 'Create Document Template', 'Admin', 'DocumentTemplate', 'Create', 'button', 2100, 2102, 'DocumentTemplates-Create'),
(2103, 'Admin.DocumentTemplate.Update', 'Edit Document Template', 'Admin', 'DocumentTemplate', 'Update', 'button', 2100, 2103, 'DocumentTemplates-Update'),
(2104, 'Admin.DocumentTemplate.Delete', 'Delete Document Template', 'Admin', 'DocumentTemplate', 'Delete', 'button', 2100, 2104, 'DocumentTemplates-Delete'),
(2150, 'Admin.EmailLog', 'Email Log', 'Admin', 'EmailLog', '', 'resource', 2000, 2150, NULL),
(2151, 'Admin.EmailLog.List', 'View Email Logs', 'Admin', 'EmailLog', 'List', 'page', 2150, 2151, 'EmailLogs-List'),
(2200, 'Admin.Export', 'Export', 'Admin', 'Export', '', 'resource', 2000, 2200, NULL),
(2201, 'Admin.Export.Customers', 'Export Customers', 'Admin', 'Export', 'Customers', 'page', 2200, 2201, 'Export-Customers'),
(2202, 'Admin.Export.Vendors', 'Export Vendors', 'Admin', 'Export', 'Vendors', 'button', 2200, 2202, 'Export-Vendors'),
(2203, 'Admin.Export.Order', 'Export Orders', 'Admin', 'Export', 'Order', 'button', 2200, 2203, 'Export-Order'),
(2250, 'Admin.Holiday', 'Holiday', 'Admin', 'Holiday', '', 'resource', 2000, 2250, NULL),
(2251, 'Admin.Holiday.List', 'View Holidays', 'Admin', 'Holiday', 'List', 'page', 2250, 2251, 'Holidays-List'),
(2252, 'Admin.Holiday.Create', 'Create Holiday', 'Admin', 'Holiday', 'Create', 'button', 2250, 2252, 'Holidays-Create'),
(2253, 'Admin.Holiday.Update', 'Edit Holiday', 'Admin', 'Holiday', 'Update', 'button', 2250, 2253, 'Holidays-Update'),
(2254, 'Admin.Holiday.Delete', 'Delete Holiday', 'Admin', 'Holiday', 'Delete', 'button', 2250, 2254, 'Holidays-Delete'),
(2300, 'Admin.ItemTag', 'Product Tag', 'Admin', 'ItemTag', '', 'resource', 2000, 2300, NULL),
(2301, 'Admin.ItemTag.List', 'View Product Tags', 'Admin', 'ItemTag', 'List', 'page', 2300, 2301, 'ItemTags-List'),
(2302, 'Admin.ItemTag.Create', 'Create Product Tag', 'Admin', 'ItemTag', 'Create', 'button', 2300, 2302, 'ItemTags-Create'),
(2303, 'Admin.ItemTag.Update', 'Edit Product Tag', 'Admin', 'ItemTag', 'Update', 'button', 2300, 2303, 'ItemTags-Update'),
(2304, 'Admin.ItemTag.Delete', 'Delete Product Tag', 'Admin', 'ItemTag', 'Delete', 'button', 2300, 2304, 'ItemTags-Delete'),
(2350, 'Admin.ItemTariff', 'Product Tariff', 'Admin', 'ItemTariff', '', 'resource', 2000, 2350, NULL),
(2351, 'Admin.ItemTariff.List', 'View Product Tariffs', 'Admin', 'ItemTariff', 'List', 'page', 2350, 2351, 'ItemTariffs-List'),
(2352, 'Admin.ItemTariff.Create', 'Create Product Tariff', 'Admin', 'ItemTariff', 'Create', 'button', 2350, 2352, 'ItemTariffs-Create'),
(2353, 'Admin.ItemTariff.Update', 'Edit Product Tariff', 'Admin', 'ItemTariff', 'Update', 'button', 2350, 2353, 'ItemTariffs-Update'),
(2354, 'Admin.ItemTariff.Delete', 'Delete Product Tariff', 'Admin', 'ItemTariff', 'Delete', 'button', 2350, 2354, 'ItemTariffs-Delete'),
(2400, 'Admin.Promotion', 'Promotion', 'Admin', 'Promotion', '', 'resource', 2000, 2400, NULL),
(2401, 'Admin.Promotion.List', 'View Promotions', 'Admin', 'Promotion', 'List', 'page', 2400, 2401, 'Promotions-List'),
(2402, 'Admin.Promotion.Create', 'Create Promotion', 'Admin', 'Promotion', 'Create', 'button', 2400, 2402, 'Promotions-Create'),
(2403, 'Admin.Promotion.Update', 'Edit Promotion', 'Admin', 'Promotion', 'Update', 'button', 2400, 2403, 'Promotions-Update'),
(2404, 'Admin.Promotion.Delete', 'Delete Promotion', 'Admin', 'Promotion', 'Delete', 'button', 2400, 2404, 'Promotions-Delete'),
(2450, 'Admin.RecalcLog', 'Recalculation Log', 'Admin', 'RecalcLog', '', 'resource', 2000, 2450, NULL),
(2451, 'Admin.RecalcLog.List', 'View Recalculation Logs', 'Admin', 'RecalcLog', 'List', 'page', 2450, 2451, 'RecalculationLogs-List'),
(2500, 'Admin.Rest365', 'Rest365', 'Admin', 'Rest365', '', 'resource', 2000, 2500, NULL),
(2501, 'Admin.Rest365.List', 'View Rest365', 'Admin', 'Rest365', 'List', 'page', 2500, 2501, 'Rest365-List'),
(2502, 'Admin.Rest365.Create', 'Create Rest365', 'Admin', 'Rest365', 'Create', 'button', 2500, 2502, 'Rest365-Create'),
(2503, 'Admin.Rest365.Update', 'Edit Rest365', 'Admin', 'Rest365', 'Update', 'button', 2500, 2503, 'Rest365-Update'),
(2504, 'Admin.Rest365.Inactive', 'Mark as Inactive', 'Admin', 'Rest365', 'Inactive', 'button', 2500, 2504, 'Rest365-Inactive'),
(2550, 'Admin.SchedulerConfig', 'Scheduler Config', 'Admin', 'SchedulerConfig', '', 'resource', 2000, 2550, NULL),
(2551, 'Admin.SchedulerConfig.List', 'View Scheduler Configs', 'Admin', 'SchedulerConfig', 'List', 'page', 2550, 2551, 'SchedulerConfigs-List'),
(2552, 'Admin.SchedulerConfig.Update', 'Edit Scheduler Config', 'Admin', 'SchedulerConfig', 'Update', 'button', 2550, 2552, 'SchedulerConfigs-Update'),
(2600, 'Admin.Term', 'Term', 'Admin', 'Term', '', 'resource', 2000, 2600, NULL),
(2601, 'Admin.Term.List', 'View Terms', 'Admin', 'Term', 'List', 'page', 2600, 2601, 'Terms-List'),
(2602, 'Admin.Term.Create', 'Create Term', 'Admin', 'Term', 'Create', 'button', 2600, 2602, 'Terms-Create'),
(2603, 'Admin.Term.Update', 'Edit Term', 'Admin', 'Term', 'Update', 'button', 2600, 2603, 'Terms-Update'),
(2604, 'Admin.Term.Delete', 'Delete Term', 'Admin', 'Term', 'Delete', 'button', 2600, 2604, 'Terms-Delete'),
(2650, 'Admin.Truck', 'Truck', 'Admin', 'Truck', '', 'resource', 2000, 2650, NULL),
(2651, 'Admin.Truck.List', 'View Trucks', 'Admin', 'Truck', 'List', 'page', 2650, 2651, 'Trucks-List'),
(2652, 'Admin.Truck.Create', 'Create Truck', 'Admin', 'Truck', 'Create', 'button', 2650, 2652, 'Trucks-Create'),
(2653, 'Admin.Truck.Update', 'Edit Truck', 'Admin', 'Truck', 'Update', 'button', 2650, 2653, 'Trucks-Update'),
(2654, 'Admin.Truck.Delete', 'Delete Truck', 'Admin', 'Truck', 'Delete', 'button', 2650, 2654, 'Trucks-Delete'),
(3000, 'Customer', 'Customer', 'Customer', '', '', 'menu', NULL, 3000, NULL),
(3050, 'Customer.Customer', 'Customer', 'Customer', 'Customer', '', 'resource', 3000, 3050, NULL),
(3051, 'Customer.Customer.List', 'View Customers', 'Customer', 'Customer', 'List', 'page', 3050, 3051, 'Customers-List'),
(3052, 'Customer.Customer.Create', 'Create Customer', 'Customer', 'Customer', 'Create', 'button', 3050, 3052, 'Customers-Create'),
(3053, 'Customer.Customer.Update', 'Edit Customer', 'Customer', 'Customer', 'Update', 'button', 3050, 3053, 'Customers-Update'),
(3054, 'Customer.Customer.Delete', 'Delete Customer', 'Customer', 'Customer', 'Delete', 'button', 3050, 3054, 'Customers-Delete'),
(3055, 'Customer.Customer.OpenClose', 'Activate or Deactivate Customer', 'Customer', 'Customer', 'OpenClose', 'button', 3050, 3055, 'Customers-OpenClose'),
(3056, 'Customer.Customer.EmailPricesheet', 'Email Price Sheet', 'Customer', 'Customer', 'EmailPricesheet', 'button', 3050, 3056, 'Customers-EmailPricesheet'),
(3057, 'Customer.Customer.EmailStatement', 'Email Statement', 'Customer', 'Customer', 'EmailStatement', 'button', 3050, 3057, 'Customers-EmailStatement'),
(3100, 'Customer.AR', 'Accounts Receivable', 'Customer', 'AR', '', 'resource', 3000, 3100, NULL),
(3101, 'Customer.AR.List', 'View Accounts Receivable', 'Customer', 'AR', 'List', 'page', 3100, 3101, 'AR-List'),
(3102, 'Customer.AR.ChargePayment', 'Charge Payment', 'Customer', 'AR', 'ChargePayment', 'button', 3100, 3102, 'AR-ChargePayment'),
(3150, 'Customer.BombSale', 'Bomb Sale', 'Customer', 'BombSale', '', 'resource', 3000, 3150, NULL),
(3151, 'Customer.BombSale.List', 'View Bomb Sales', 'Customer', 'BombSale', 'List', 'page', 3150, 3151, 'TempBombSales-List'),
(3152, 'Customer.BombSale.Update', 'Edit Bomb Sale Detail', 'Customer', 'BombSale', 'Update', 'button', 3150, 3152, 'TempBombSales-Update'),
(3153, 'Customer.BombSale.Save', 'Save Bomb Sale', 'Customer', 'BombSale', 'Save', 'button', 3150, 3153, 'TempBombSales-SaveBomb'),
(3200, 'Customer.CustomerPayment', 'Customer Payment', 'Customer', 'CustomerPayment', '', 'resource', 3000, 3200, NULL),
(3201, 'Customer.CustomerPayment.List', 'View Customer Payments', 'Customer', 'CustomerPayment', 'List', 'page', 3200, 3201, 'CustomerPayments-List'),
(3202, 'Customer.CustomerPayment.Save', 'Create or Edit Customer Payment', 'Customer', 'CustomerPayment', 'Save', 'button', 3200, 3202, 'CustomerPayments-Save'),
(3203, 'Customer.CustomerPayment.Delete', 'Delete Customer Payment', 'Customer', 'CustomerPayment', 'Delete', 'button', 3200, 3203, 'CustomerPayments-Delete'),
(3204, 'Customer.CustomerPayment.SaveReturn', 'Return Payment', 'Customer', 'CustomerPayment', 'SaveReturn', 'button', 3200, 3204, 'CustomerPayments-SaveReturn'),
(3205, 'Customer.CustomerPayment.DeleteReturn', 'Delete Return Payment', 'Customer', 'CustomerPayment', 'DeleteReturn', 'button', 3200, 3205, 'CustomerPayments-DeleteReturn'),
(3250, 'Customer.Deposit', 'Deposit', 'Customer', 'Deposit', '', 'resource', 3000, 3250, NULL),
(3251, 'Customer.Deposit.List', 'View Deposits', 'Customer', 'Deposit', 'List', 'page', 3250, 3251, 'Deposits-List'),
(3252, 'Customer.Deposit.Save', 'Create or Edit Deposit', 'Customer', 'Deposit', 'Save', 'button', 3250, 3252, 'Deposits-Save'),
(3253, 'Customer.Deposit.Delete', 'Delete Deposit', 'Customer', 'Deposit', 'Delete', 'button', 3250, 3253, 'Deposits-Delete'),
(3300, 'Customer.PaymentMethod', 'Payment Method', 'Customer', 'PaymentMethod', '', 'resource', 3000, 3300, NULL),
(3301, 'Customer.PaymentMethod.Create', 'Create Payment Method', 'Customer', 'PaymentMethod', 'Create', 'button', 3300, 3301, 'PaymentMethods-Create'),
(3302, 'Customer.PaymentMethod.Delete', 'Delete Payment Method', 'Customer', 'PaymentMethod', 'Delete', 'button', 3300, 3302, 'PaymentMethods-Delete'),
(3350, 'Customer.Sale', 'Sales Order', 'Customer', 'Sale', '', 'resource', 3000, 3350, NULL),
(3351, 'Customer.Sale.List', 'View Sales Orders', 'Customer', 'Sale', 'List', 'page', 3350, 3351, 'Sales-List'),
(3352, 'Customer.Sale.Create', 'Create Sales Order', 'Customer', 'Sale', 'Create', 'button', 3350, 3352, 'Sales-Checkout'),
(3353, 'Customer.Sale.Update', 'Edit Sales Order', 'Customer', 'Sale', 'Update', 'button', 3350, 3353, 'Sales-UpdatePartially'),
(3354, 'Customer.Sale.Delete', 'Delete Sales Order', 'Customer', 'Sale', 'Delete', 'button', 3350, 3354, 'Sales-Delete'),
(3355, 'Customer.Sale.UpdateRoute', 'Edit Route', 'Customer', 'Sale', 'UpdateRoute', 'button', 3350, 3355, 'Sales-UpdateRoute'),
(3356, 'Customer.Sale.UpdateStage', 'Edit Stage', 'Customer', 'Sale', 'UpdateStage', 'button', 3350, 3356, 'Sales-UpdateStage'),
(3357, 'Customer.Sale.UpdateInstruction', 'Edit Instruction', 'Customer', 'Sale', 'UpdateInstruction', 'button', 3350, 3357, 'Sales-UpdateInstruction'),
(3358, 'Customer.Sale.UpdatePO', 'Edit Purchase Order Number', 'Customer', 'Sale', 'UpdatePO', 'button', 3350, 3358, 'Sales-UpdatePO'),
(3359, 'Customer.Sale.UpdateLoadSeparate', 'Edit Load Separate', 'Customer', 'Sale', 'UpdateLoadSeparate', 'button', 3350, 3359, 'Sales-UpdateLoadSeparate'),
(3360, 'Customer.Sale.UpdateCarrier', 'Edit Carrier', 'Customer', 'Sale', 'UpdateCarrier', 'button', 3350, 3360, 'Sales-UpdateCarrier'),
(3361, 'Customer.Sale.ShippingCharge', 'Add Shipping Charge', 'Customer', 'Sale', 'ShippingCharge', 'button', 3350, 3361, 'Sales-ShippingCharge'),
(3362, 'Customer.Sale.SeePdf', 'View PDF Document', 'Customer', 'Sale', 'SeePdf', 'button', 3350, 3362, 'Sales-SeePdf'),
(3363, 'Customer.Sale.EmailPdf', 'Email PDF Document', 'Customer', 'Sale', 'EmailPdf', 'button', 3350, 3363, 'Sales-EmailPdf'),
(3364, 'Customer.Sale.MergeOrder', 'Merge Sales Order', 'Customer', 'Sale', 'MergeOrder', 'button', 3350, 3364, 'Sales-MergeOrder'),
(3365, 'Customer.Sale.MergePdf', 'Merge PDF Document', 'Customer', 'Sale', 'MergePdf', 'button', 3350, 3365, 'Sales-MergePdf'),
(3366, 'Customer.Sale.SeePayment', 'View Payment', 'Customer', 'Sale', 'SeePayment', 'button', 3350, 3366, 'Sales-SeePayment'),
(4000, 'Employee', 'Employee', 'Employee', '', '', 'menu', NULL, 4000, NULL),
(4050, 'Employee.Employee', 'Employee', 'Employee', 'Employee', '', 'resource', 4000, 4050, NULL),
(4051, 'Employee.Employee.List', 'View Employees', 'Employee', 'Employee', 'List', 'page', 4050, 4051, 'Employees-List'),
(4052, 'Employee.Employee.Create', 'Create Employee', 'Employee', 'Employee', 'Create', 'button', 4050, 4052, 'Employees-Create'),
(4053, 'Employee.Employee.Update', 'Edit Employee', 'Employee', 'Employee', 'Update', 'button', 4050, 4053, 'Employees-Update'),
(4054, 'Employee.Employee.Delete', 'Delete Employee', 'Employee', 'Employee', 'Delete', 'button', 4050, 4054, 'Employees-Delete'),
(4100, 'Employee.EmpAdvance', 'Employee Advance', 'Employee', 'EmpAdvance', '', 'resource', 4000, 4100, NULL),
(4101, 'Employee.EmpAdvance.List', 'View Employee Advances', 'Employee', 'EmpAdvance', 'List', 'page', 4100, 4101, 'EmpAdvances-List'),
(4102, 'Employee.EmpAdvance.Save', 'Create or Edit Advance Payment', 'Employee', 'EmpAdvance', 'Save', 'button', 4100, 4102, 'EmpAdvances-Save'),
(4103, 'Employee.EmpAdvance.Delete', 'Delete Advance Payment', 'Employee', 'EmpAdvance', 'Delete', 'button', 4100, 4103, 'EmpAdvances-Delete'),
(4150, 'Employee.Payroll', 'Payroll', 'Employee', 'Payroll', '', 'resource', 4000, 4150, NULL),
(4151, 'Employee.Payroll.List', 'View Payrolls', 'Employee', 'Payroll', 'List', 'page', 4150, 4151, 'Payrolls-List'),
(4152, 'Employee.Payroll.Save', 'Create or Edit Payroll', 'Employee', 'Payroll', 'Save', 'button', 4150, 4152, 'Payrolls-Save'),
(4153, 'Employee.Payroll.Delete', 'Delete Payroll', 'Employee', 'Payroll', 'Delete', 'button', 4150, 4153, 'Payrolls-Delete'),
(4154, 'Employee.Payroll.Import', 'Import Payroll', 'Employee', 'Payroll', 'Import', 'button', 4150, 4154, 'Payrolls-Import'),
(4200, 'Employee.PayrollService', 'Payroll Service', 'Employee', 'PayrollService', '', 'resource', 4000, 4200, NULL),
(4201, 'Employee.PayrollService.List', 'View Payroll Services', 'Employee', 'PayrollService', 'List', 'page', 4200, 4201, 'PayrollServices-List'),
(4202, 'Employee.PayrollService.Save', 'Create or Edit Payroll Service', 'Employee', 'PayrollService', 'Save', 'button', 4200, 4202, 'PayrollServices-Save'),
(4203, 'Employee.PayrollService.Delete', 'Delete Payroll Service', 'Employee', 'PayrollService', 'Delete', 'button', 4200, 4203, 'PayrollServices-Delete'),
(4250, 'Employee.Timesheet', 'Timesheet', 'Employee', 'Timesheet', '', 'resource', 4000, 4250, NULL),
(4251, 'Employee.Timesheet.List', 'View Timesheets', 'Employee', 'Timesheet', 'List', 'page', 4250, 4251, 'Timesheets-List'),
(4252, 'Employee.Timesheet.Save', 'Create or Edit Timesheet', 'Employee', 'Timesheet', 'Save', 'button', 4250, 4252, 'Timesheets-Save'),
(4253, 'Employee.Timesheet.Delete', 'Delete Timesheet', 'Employee', 'Timesheet', 'Delete', 'button', 4250, 4253, 'Timesheets-Delete'),
(5000, 'Product', 'Product', 'Product', '', '', 'menu', NULL, 5000, NULL),
(5050, 'Product.Item', 'Product', 'Product', 'Item', '', 'resource', 5000, 5050, NULL),
(5051, 'Product.Item.List', 'View Products', 'Product', 'Item', 'List', 'page', 5050, 5051, 'Items-List'),
(5052, 'Product.Item.Save', 'Create or Edit Product', 'Product', 'Item', 'Save', 'button', 5050, 5052, 'Items-Save'),
(5053, 'Product.Item.Delete', 'Delete Product', 'Product', 'Item', 'Delete', 'button', 5050, 5053, 'Items-Delete'),
(5054, 'Product.Item.UpdateBaseP1', 'Edit Base Price (P1)', 'Product', 'Item', 'UpdateBaseP1', 'button', 5050, 5054, 'Items-UpdateBaseP1'),
(5055, 'Product.Item.UpdateInventorySettings', 'Edit Inventory Settings', 'Product', 'Item', 'UpdateInventorySettings', 'button', 5050, 5055, 'Items-UpdateInventorySettings'),
(5056, 'Product.Item.CreateItemUnit', 'Create Product Unit', 'Product', 'Item', 'CreateItemUnit', 'button', 5050, 5056, 'Items-CreateItemUnit'),
(5057, 'Product.Item.UpdateItemUnit', 'Edit Product Unit', 'Product', 'Item', 'UpdateItemUnit', 'button', 5050, 5057, 'Items-UpdateItemUnit'),
(5058, 'Product.Item.DeleteItemUnit', 'Delete Product Unit', 'Product', 'Item', 'DeleteItemUnit', 'button', 5050, 5058, 'Items-DeleteItemUnit'),
(5100, 'Product.InventoryAdj', 'Inventory Adjustment', 'Product', 'InventoryAdj', '', 'resource', 5000, 5100, NULL),
(5101, 'Product.InventoryAdj.List', 'View Inventory Adjustments', 'Product', 'InventoryAdj', 'List', 'page', 5100, 5101, 'InventoryAdjs-List'),
(5102, 'Product.InventoryAdj.Save', 'Create or Edit Adjustment', 'Product', 'InventoryAdj', 'Save', 'button', 5100, 5102, 'InventoryAdjs-Save'),
(5103, 'Product.InventoryAdj.Delete', 'Delete Adjustment', 'Product', 'InventoryAdj', 'Delete', 'button', 5100, 5103, 'InventoryAdjs-Delete'),
(5104, 'Product.InventoryAdj.DeleteDetail', 'Delete Adjustment Detail', 'Product', 'InventoryAdj', 'DeleteDetail', 'button', 5100, 5104, 'InventoryAdjs-DeleteDetail'),
(5105, 'Product.InventoryAdj.QtyAdj', 'Quantity Adjustment', 'Product', 'InventoryAdj', 'QtyAdj', 'button', 5100, 5105, 'InventoryAdjs-QtyAdj'),
(5150, 'Product.ItemCategory', 'Product Category', 'Product', 'ItemCategory', '', 'resource', 5000, 5150, NULL),
(5151, 'Product.ItemCategory.List', 'View Product Categories', 'Product', 'ItemCategory', 'List', 'page', 5150, 5151, 'ItemCategories-List'),
(5152, 'Product.ItemCategory.Create', 'Create Product Category', 'Product', 'ItemCategory', 'Create', 'button', 5150, 5152, 'ItemCategories-Create'),
(5153, 'Product.ItemCategory.Update', 'Edit Product Category', 'Product', 'ItemCategory', 'Update', 'button', 5150, 5153, 'ItemCategories-Update'),
(5154, 'Product.ItemCategory.Delete', 'Delete Product Category', 'Product', 'ItemCategory', 'Delete', 'button', 5150, 5154, 'ItemCategories-Delete'),
(5155, 'Product.ItemCategory.Reorder', 'Reorder Product Category', 'Product', 'ItemCategory', 'Reorder', 'button', 5150, 5155, 'ItemCategories-ReorderNode'),
(5200, 'Product.ItemHistory', 'Product History', 'Product', 'ItemHistory', '', 'resource', 5000, 5200, NULL),
(5201, 'Product.ItemHistory.Sales', 'View Sales History', 'Product', 'ItemHistory', 'Sales', 'page', 5200, 5201, 'ItemHistories-Sales'),
(5202, 'Product.ItemHistory.Purchase', 'View Cost History', 'Product', 'ItemHistory', 'Purchase', 'button', 5200, 5202, 'ItemHistories-Purchase'),
(5203, 'Product.ItemHistory.Inventory', 'View Inventory History', 'Product', 'ItemHistory', 'Inventory', 'button', 5200, 5203, 'ItemHistories-Inventory'),
(5204, 'Product.ItemHistory.SalesCost', 'View Sales and Cost History', 'Product', 'ItemHistory', 'SalesCost', 'button', 5200, 5204, 'ItemHistories-SalesCost'),
(5205, 'Product.ItemHistory.Adjustment', 'View Adjustment History', 'Product', 'ItemHistory', 'Adjustment', 'button', 5200, 5205, 'ItemHistories-Adjustment'),
(5250, 'Product.ItemImage', 'Product Image', 'Product', 'ItemImage', '', 'resource', 5000, 5250, NULL),
(5251, 'Product.ItemImage.List', 'View Product Images', 'Product', 'ItemImage', 'List', 'page', 5250, 5251, 'ItemImages-List'),
(5252, 'Product.ItemImage.Upload', 'Upload Product Image', 'Product', 'ItemImage', 'Upload', 'button', 5250, 5252, 'ItemImages-Upload'),
(5253, 'Product.ItemImage.Delete', 'Delete Product Image', 'Product', 'ItemImage', 'Delete', 'button', 5250, 5253, 'ItemImages-Delete'),
(5300, 'Product.ItemStorage', 'Product Storage', 'Product', 'ItemStorage', '', 'resource', 5000, 5300, NULL),
(5301, 'Product.ItemStorage.List', 'View Product Storages', 'Product', 'ItemStorage', 'List', 'page', 5300, 5301, 'ItemStorages-List'),
(5302, 'Product.ItemStorage.Create', 'Create Product Storage', 'Product', 'ItemStorage', 'Create', 'button', 5300, 5302, 'ItemStorages-Create'),
(5303, 'Product.ItemStorage.Update', 'Edit Product Storage', 'Product', 'ItemStorage', 'Update', 'button', 5300, 5303, 'ItemStorages-Update'),
(5304, 'Product.ItemStorage.Delete', 'Delete Product Storage', 'Product', 'ItemStorage', 'Delete', 'button', 5300, 5304, 'ItemStorages-Delete'),
(6000, 'Report', 'Report', 'Report', '', '', 'menu', NULL, 6000, NULL),
(6050, 'Report.AP', 'Accounts Payable', 'Report', 'AP', '', 'resource', 6000, 6050, NULL),
(6051, 'Report.AP.APCheck', 'Accounts Payable Check', 'Report', 'AP', 'APCheck', 'page', 6050, 6051, 'Reports-APCheck'),
(6052, 'Report.AP.CheckToBePrinted', 'Checks To Be Printed', 'Report', 'AP', 'CheckToBePrinted', 'page', 6050, 6052, 'Reports-CheckToBePrinted'),
(6053, 'Report.AP.APInvoice', 'Accounts Payable From Invoice', 'Report', 'AP', 'APInvoice', 'page', 6050, 6053, 'Reports-APInvoice'),
(6100, 'Report.AR', 'Accounts Receivable', 'Report', 'AR', '', 'resource', 6000, 6100, NULL),
(6101, 'Report.AR.ARInvoice', 'Accounts Receivable From Invoice', 'Report', 'AR', 'ARInvoice', 'page', 6100, 6101, 'Reports-ARInvoice'),
(6102, 'Report.AR.ARMonth', 'Accounts Receivable by Month', 'Report', 'AR', 'ARMonth', 'page', 6100, 6102, 'Reports-ARMonth'),
(6150, 'Report.Banking', 'Banking Report', 'Report', 'Banking', '', 'resource', 6000, 6150, NULL),
(6151, 'Report.Banking.BankRecon', 'Bank Reconciliation', 'Report', 'Banking', 'BankRecon', 'page', 6150, 6151, 'Reports-BankRecon'),
(6152, 'Report.Banking.PmtReceipt', 'Payment Receipt', 'Report', 'Banking', 'PmtReceipt', 'page', 6150, 6152, 'Reports-PmtReceipt'),
(6200, 'Report.Customer', 'Customer Report', 'Report', 'Customer', '', 'resource', 6000, 6200, NULL),
(6201, 'Report.Customer.DescDollar', 'Descending Dollar', 'Report', 'Customer', 'DescDollar', 'page', 6200, 6201, 'Reports-DescDollar'),
(6202, 'Report.Customer.PaymentHistory', 'Payment History', 'Report', 'Customer', 'PaymentHistory', 'page', 6200, 6202, 'Reports-PaymentHistory'),
(6203, 'Report.Customer.Statement', 'Customer Statement', 'Report', 'Customer', 'Statement', 'page', 6200, 6203, 'Reports-CustStmt'),
(6204, 'Report.Customer.AccountHistory', 'Account History', 'Report', 'Customer', 'AccountHistory', 'page', 6200, 6204, 'Reports-AccountHistory'),
(6205, 'Report.Customer.Pricesheet', 'Price Sheet', 'Report', 'Customer', 'Pricesheet', 'page', 6200, 6205, 'Reports-Pricesheet'),
(6206, 'Report.Customer.OrderGuide', 'Order Guide', 'Report', 'Customer', 'OrderGuide', 'page', 6200, 6206, 'Reports-OrderGuide'),
(6207, 'Report.Customer.ItemVolume', 'Product Volume History', 'Report', 'Customer', 'ItemVolume', 'page', 6200, 6207, 'Reports-CustItemVolume'),
(6208, 'Report.Customer.SalesByItem', 'Customer Sales by Product', 'Report', 'Customer', 'SalesByItem', 'page', 6200, 6208, 'Reports-CustSalesByItem'),
(6209, 'Report.Customer.SalesHistory', 'Sales History', 'Report', 'Customer', 'SalesHistory', 'page', 6200, 6209, 'Reports-SalesHistory'),
(6210, 'Report.Customer.CustPayment', 'Customer Payment', 'Report', 'Customer', 'CustPayment', 'page', 6200, 6210, 'Reports-CustPayment'),
(6250, 'Report.Inventory', 'Inventory Report', 'Report', 'Inventory', '', 'resource', 6000, 6250, NULL),
(6251, 'Report.Inventory.InventoryStatus', 'Inventory Status', 'Report', 'Inventory', 'InventoryStatus', 'page', 6250, 6251, 'Reports-InventoryStatus'),
(6252, 'Report.Inventory.Reorder', 'Reorder', 'Report', 'Inventory', 'Reorder', 'page', 6250, 6252, 'Reports-Reorder'),
(6253, 'Report.Inventory.InventoryValuation', 'Inventory Valuation', 'Report', 'Inventory', 'InventoryValuation', 'page', 6250, 6253, 'Reports-InventoryValuation'),
(6254, 'Report.Inventory.InventoryMovement', 'Inventory Movement', 'Report', 'Inventory', 'InventoryMovement', 'page', 6250, 6254, 'Reports-InventoryMovement'),
(6255, 'Report.Inventory.InventoryIncoming', 'Incoming Purchases', 'Report', 'Inventory', 'InventoryIncoming', 'page', 6250, 6255, 'Reports-InventoryIncoming'),
(6300, 'Report.Payroll', 'Payroll Report', 'Report', 'Payroll', '', 'resource', 6000, 6300, NULL),
(6301, 'Report.Payroll.Payroll', 'Payroll', 'Report', 'Payroll', 'Payroll', 'page', 6300, 6301, 'Reports-Payroll'),
(6302, 'Report.Payroll.EmpLoanLedger', 'Employee Loan Ledger', 'Report', 'Payroll', 'EmpLoanLedger', 'page', 6300, 6302, 'Reports-EmpLoanLedger'),
(6350, 'Report.PL', 'Profit and Loss', 'Report', 'PL', '', 'resource', 6000, 6350, NULL),
(6351, 'Report.PL.BalanceSheet', 'Balance Sheet', 'Report', 'PL', 'BalanceSheet', 'page', 6350, 6351, 'Reports-BalanceSheet'),
(6352, 'Report.PL.ProfitLoss', 'Profit and Loss', 'Report', 'PL', 'ProfitLoss', 'page', 6350, 6352, 'Reports-ProfitLoss'),
(6353, 'Report.PL.Ledger', 'Ledger by Account', 'Report', 'PL', 'Ledger', 'page', 6350, 6353, 'Reports-Ledger'),
(6354, 'Report.PL.LedgerByPayee', 'Ledger By Payee', 'Report', 'PL', 'LedgerByPayee', 'page', 6350, 6354, 'Reports-LedgerByPayee'),
(6400, 'Report.Sales', 'Sales Report', 'Report', 'Sales', '', 'resource', 6000, 6400, NULL),
(6401, 'Report.Sales.SalesDaily', 'Sales Daily', 'Report', 'Sales', 'SalesDaily', 'page', 6400, 6401, 'Reports-SalesDaily'),
(6402, 'Report.Sales.SalesTax', 'Sales Tax', 'Report', 'Sales', 'SalesTax', 'page', 6400, 6402, 'Reports-SalesTax'),
(6403, 'Report.Sales.Responsible', 'Sales by Responsible', 'Report', 'Sales', 'Responsible', 'page', 6400, 6403, 'Reports-Responsible'),
(6404, 'Report.Sales.DailySummary', 'Daily Summary', 'Report', 'Sales', 'DailySummary', 'page', 6400, 6404, 'Reports-DailySummary'),
(6405, 'Report.Sales.CreditMemo', 'Credit Memo', 'Report', 'Sales', 'CreditMemo', 'page', 6400, 6405, 'Reports-CreditMemo'),
(6406, 'Report.Sales.SalesByItem', 'Sales By Item', 'Report', 'Sales', 'SalesByItem', 'page', 6400, 6406, 'Reports-SalesByItem'),
(6407, 'Report.Sales.SalesDetail', 'Sales Detail', 'Report', 'Sales', 'SalesDetail', 'page', 6400, 6407, 'Reports-SalesDetail'),
(6408, 'Report.Sales.SalesDaily2', 'Sales Daily 2', 'Report', 'Sales', 'SalesDaily2', 'page', 6400, 6408, 'Reports-SalesDaily2'),
(6412, 'Report.Sales.SalesByInvoice', 'Sales By Invoice', 'Report', 'Sales', 'SalesByInvoice', 'page', 6400, 6412, 'Reports-SalesByInvoice'),
(6409, 'Report.Sales.SalesYearly', 'Sales Yearly', 'Report', 'Sales', 'SalesYearly', 'page', 6400, 6409, 'Reports-SalesYearly'),
(6410, 'Report.Sales.SalesCommission', 'Sales Commission', 'Report', 'Sales', 'SalesCommission', 'page', 6400, 6410, 'Reports-SalesCommission'),
(6411, 'Report.Sales.SalesCommission2', 'Sales Commission 2', 'Report', 'Sales', 'SalesCommission2', 'page', 6400, 6411, 'Reports-SalesCommission2'),
-- 2026-05-13: added Customer Sales Summary page.
(6415, 'Report.Sales.CustomerSalesSummary', 'Customer Sales Summary', 'Report', 'Sales', 'CustomerSalesSummary', 'page', 6400, 6415, NULL),
-- 2026-05-14: added Sales Summary (period-over-period trend) page.
(6416, 'Report.Sales.SalesSummary', 'Sales Summary', 'Report', 'Sales', 'SalesSummary', 'page', 6400, 6416, NULL),
(6450, 'Report.Timesheet', 'Timesheet Report', 'Report', 'Timesheet', '', 'resource', 6000, 6450, NULL),
(6451, 'Report.Timesheet.Timesheet', 'Timesheet', 'Report', 'Timesheet', 'Timesheet', 'page', 6450, 6451, 'Reports-Timesheet'),
(6452, 'Report.Timesheet.JobSummary', 'Job Summary', 'Report', 'Timesheet', 'JobSummary', 'page', 6450, 6452, 'Reports-JobSummary'),
-- 2026-05-10: added Report.Purchase namespace + Vendor Purchase Summary page.
(6500, 'Report.Purchase', 'Purchase Report', 'Report', 'Purchase', '', 'resource', 6000, 6500, NULL),
(6501, 'Report.Purchase.VendorPurchaseSummary', 'Vendor Purchase Summary', 'Report', 'Purchase', 'VendorPurchaseSummary', 'page', 6500, 6501, NULL),
(7000, 'Vendor', 'Vendor', 'Vendor', '', '', 'menu', NULL, 7000, NULL),
(7050, 'Vendor.Vendor', 'Vendor', 'Vendor', 'Vendor', '', 'resource', 7000, 7050, NULL),
(7051, 'Vendor.Vendor.List', 'View Vendors', 'Vendor', 'Vendor', 'List', 'page', 7050, 7051, 'Vendors-List'),
(7052, 'Vendor.Vendor.Create', 'Create Vendor', 'Vendor', 'Vendor', 'Create', 'button', 7050, 7052, 'Vendors-Create'),
(7053, 'Vendor.Vendor.Update', 'Edit Vendor', 'Vendor', 'Vendor', 'Update', 'button', 7050, 7053, 'Vendors-Update'),
(7054, 'Vendor.Vendor.Delete', 'Delete Vendor', 'Vendor', 'Vendor', 'Delete', 'button', 7050, 7054, 'Vendors-Delete'),
(7055, 'Vendor.Vendor.OpenClose', 'Activate or Deactivate Vendor', 'Vendor', 'Vendor', 'OpenClose', 'button', 7050, 7055, 'Vendors-OpenClose'),
(7100, 'Vendor.Liability', 'Liability', 'Vendor', 'Liability', '', 'resource', 7000, 7100, NULL),
(7101, 'Vendor.Liability.LoanList', 'View Loans', 'Vendor', 'Liability', 'LoanList', 'page', 7100, 7101, 'Liabilities-LoanList'),
(7102, 'Vendor.Liability.TaxList', 'View Tax Liabilities', 'Vendor', 'Liability', 'TaxList', 'page', 7100, 7102, 'Liabilities-TaxList'),
(7103, 'Vendor.Liability.CCList', 'View Credit Cards', 'Vendor', 'Liability', 'CCList', 'page', 7100, 7103, 'Liabilities-CCList'),
(7104, 'Vendor.Liability.Create', 'Create Liability', 'Vendor', 'Liability', 'Create', 'button', 7100, 7104, 'Liabilities-Create'),
(7105, 'Vendor.Liability.Update', 'Edit Liability', 'Vendor', 'Liability', 'Update', 'button', 7100, 7105, 'Liabilities-Update'),
(7106, 'Vendor.Liability.Delete', 'Delete Liability', 'Vendor', 'Liability', 'Delete', 'button', 7100, 7106, 'Liabilities-Delete'),
(7107, 'Vendor.Liability.DeletePayment', 'Delete Payment', 'Vendor', 'Liability', 'DeletePayment', 'button', 7100, 7107, 'Liabilities-DeletePayment'),
(7108, 'Vendor.Liability.TxList', 'View Transactions', 'Vendor', 'Liability', 'TxList', 'button', 7100, 7108, 'Liabilities-TxList'),
(7109, 'Vendor.Liability.SaveLoanPayment', 'Create or Edit Loan Payment', 'Vendor', 'Liability', 'SaveLoanPayment', 'button', 7100, 7109, 'Liabilities-SaveLoanPayment'),
(7110, 'Vendor.Liability.SaveCCPayment', 'Create or Edit Credit Card Payment', 'Vendor', 'Liability', 'SaveCCPayment', 'button', 7100, 7110, 'Liabilities-SaveCCPayment'),
(7111, 'Vendor.Liability.ImportTaxPayment', 'Import Tax Payment', 'Vendor', 'Liability', 'ImportTaxPayment', 'button', 7100, 7111, 'Liabilities-ImportTaxPayment'),
(7150, 'Vendor.Purchase', 'Purchase Bill', 'Vendor', 'Purchase', '', 'resource', 7000, 7150, NULL),
(7151, 'Vendor.Purchase.List', 'View Purchase Bills', 'Vendor', 'Purchase', 'List', 'page', 7150, 7151, 'Purchases-List'),
(7152, 'Vendor.Purchase.Create', 'Create Purchase Bill', 'Vendor', 'Purchase', 'Create', 'button', 7150, 7152, 'Purchases-Checkout'),
(7153, 'Vendor.Purchase.Update', 'Edit Purchase Bill', 'Vendor', 'Purchase', 'Update', 'button', 7150, 7153, 'Purchases-UpdatePartially'),
(7154, 'Vendor.Purchase.Delete', 'Delete Purchase Bill', 'Vendor', 'Purchase', 'Delete', 'button', 7150, 7154, 'Purchases-Delete'),
(7155, 'Vendor.Purchase.UpdateDocNumber', 'Edit Document Number', 'Vendor', 'Purchase', 'UpdateDocNumber', 'button', 7150, 7155, 'Purchases-UpdateDocNumber'),
(7156, 'Vendor.Purchase.UpdateInvoiceDate', 'Edit Invoice Date', 'Vendor', 'Purchase', 'UpdateInvoiceDate', 'button', 7150, 7156, 'Purchases-UpdateInvoiceDate'),
(7157, 'Vendor.Purchase.UpdateCommission', 'Edit Commission', 'Vendor', 'Purchase', 'UpdateCommission', 'button', 7150, 7157, 'Purchases-UpdateCommission'),
(7158, 'Vendor.Purchase.UpdatePallet', 'Edit Pallet', 'Vendor', 'Purchase', 'UpdatePallet', 'button', 7150, 7158, 'Purchases-UpdatePallet'),
(7159, 'Vendor.Purchase.UpdateContainer', 'Edit Container', 'Vendor', 'Purchase', 'UpdateContainer', 'button', 7150, 7159, 'Purchases-UpdateContainer'),
(7160, 'Vendor.Purchase.SeePdf', 'View Bill PDF', 'Vendor', 'Purchase', 'SeePdf', 'button', 7150, 7160, 'Purchases-SeePdf'),
(7161, 'Vendor.Purchase.UploadBillPDF', 'Upload Bill PDF', 'Vendor', 'Purchase', 'UploadBillPDF', 'button', 7150, 7161, 'Purchases-UploadBillPDF'),
(7162, 'Vendor.Purchase.AssignShipment', 'Assign Shipment', 'Vendor', 'Purchase', 'AssignShipment', 'button', 7150, 7162, 'Purchases-AssignShipment'),
(7200, 'Vendor.PurchaseOrder', 'Purchase Order', 'Vendor', 'PurchaseOrder', '', 'resource', 7000, 7200, NULL),
(7201, 'Vendor.PurchaseOrder.List', 'View Purchase Orders', 'Vendor', 'PurchaseOrder', 'List', 'page', 7200, 7201, 'PurchaseOrders-List'),
(7202, 'Vendor.PurchaseOrder.Create', 'Create or Edit Purchase Order', 'Vendor', 'PurchaseOrder', 'Create', 'button', 7200, 7202, 'PurchaseOrders-Checkout'),
(7203, 'Vendor.PurchaseOrder.Delete', 'Delete Purchase Order', 'Vendor', 'PurchaseOrder', 'Delete', 'button', 7200, 7203, 'PurchaseOrders-Delete'),
(7204, 'Vendor.PurchaseOrder.Print', 'Print Purchase Order', 'Vendor', 'PurchaseOrder', 'Print', 'button', 7200, 7204, 'PurchaseOrders-PrintPO'),
(7205, 'Vendor.PurchaseOrder.CopyToBill', 'Receive Product', 'Vendor', 'PurchaseOrder', 'CopyToBill', 'button', 7200, 7205, 'PurchaseOrders-CopyToBill'),
(7206, 'Vendor.PurchaseOrder.ConvertToBill', 'Convert to Bill', 'Vendor', 'PurchaseOrder', 'ConvertToBill', 'button', 7200, 7206, 'PurchaseOrders-UpdateToBillStage'),
(7207, 'Vendor.PurchaseOrder.GetAdvances', 'View Advance Payments', 'Vendor', 'PurchaseOrder', 'GetAdvances', 'button', 7200, 7207, 'PurchaseOrders-GetAdvances'),
(7208, 'Vendor.PurchaseOrder.SaveAdvance', 'Create or Edit Advance Payment', 'Vendor', 'PurchaseOrder', 'SaveAdvance', 'button', 7200, 7208, 'PurchaseOrders-SaveAdvance'),
(7209, 'Vendor.PurchaseOrder.DeleteAdvance', 'Delete Advance Payment', 'Vendor', 'PurchaseOrder', 'DeleteAdvance', 'button', 7200, 7209, 'PurchaseOrders-DeleteAdvance'),
(7250, 'Vendor.Shipment', 'Shipment', 'Vendor', 'Shipment', '', 'resource', 7000, 7250, NULL),
(7251, 'Vendor.Shipment.List', 'View Shipments', 'Vendor', 'Shipment', 'List', 'page', 7250, 7251, 'Shipments-List'),
(7252, 'Vendor.Shipment.Create', 'Create Shipment', 'Vendor', 'Shipment', 'Create', 'button', 7250, 7252, 'Shipments-Create'),
(7253, 'Vendor.Shipment.Update', 'Edit Shipment', 'Vendor', 'Shipment', 'Update', 'button', 7250, 7253, 'Shipments-Update'),
(7254, 'Vendor.Shipment.Delete', 'Delete Shipment', 'Vendor', 'Shipment', 'Delete', 'button', 7250, 7254, 'Shipments-Delete'),
(7255, 'Vendor.Shipment.Reopen', 'Reopen Shipment', 'Vendor', 'Shipment', 'Reopen', 'button', 7250, 7255, 'Shipments-Reopen'),
(7256, 'Vendor.Shipment.GenerateBill', 'Generate Bill', 'Vendor', 'Shipment', 'GenerateBill', 'button', 7250, 7256, 'Shipments-GenerateBill'),
(7257, 'Vendor.Shipment.UnAllocation', 'Unallocate Shipment', 'Vendor', 'Shipment', 'UnAllocation', 'button', 7250, 7257, 'Shipments-UnAllocation'),
(7300, 'Vendor.VendorPayment', 'Vendor Payment', 'Vendor', 'VendorPayment', '', 'resource', 7000, 7300, NULL),
(7301, 'Vendor.VendorPayment.List', 'View Vendor Payments', 'Vendor', 'VendorPayment', 'List', 'page', 7300, 7301, 'VendorPayments-List'),
(7302, 'Vendor.VendorPayment.Save', 'Create or Edit Vendor Payment', 'Vendor', 'VendorPayment', 'Save', 'button', 7300, 7302, 'VendorPayments-Save'),
(7303, 'Vendor.VendorPayment.Delete', 'Delete Vendor Payment', 'Vendor', 'VendorPayment', 'Delete', 'button', 7300, 7303, 'VendorPayments-Delete'),
(7304, 'Vendor.VendorPayment.VoidCheck', 'Void Check', 'Vendor', 'VendorPayment', 'VoidCheck', 'button', 7300, 7304, 'VendorPayments-VoidCheck'),
(7305, 'Vendor.VendorPayment.UnVoidCheck', 'Unvoid Check', 'Vendor', 'VendorPayment', 'UnVoidCheck', 'button', 7300, 7305, 'VendorPayments-UnVoidCheck'),
(7306, 'Vendor.VendorPayment.Return', 'Create Return Payment', 'Vendor', 'VendorPayment', 'Return', 'button', 7300, 7306, 'VendorPayments-Return'),
(7307, 'Vendor.VendorPayment.DeleteReturn', 'Delete Return Payment', 'Vendor', 'VendorPayment', 'DeleteReturn', 'button', 7300, 7307, 'VendorPayments-DeleteReturn'),
(7308, 'Vendor.VendorPayment.SavePayNow', 'Create or Edit Pay Now', 'Vendor', 'VendorPayment', 'SavePayNow', 'button', 7300, 7308, 'VendorPayments-SavePayNow'),
(7309, 'Vendor.VendorPayment.ImportPayNow', 'Import Pay Now', 'Vendor', 'VendorPayment', 'ImportPayNow', 'button', 7300, 7309, 'VendorPayments-ImportPayNow'),
(7310, 'Vendor.VendorPayment.ApplyAdvance', 'Apply Advance Payment', 'Vendor', 'VendorPayment', 'ApplyAdvance', 'button', 7300, 7310, 'VendorPayments-ApplyAdvance'),
(7311, 'Vendor.VendorPayment.UnapplyAdvance', 'Unapply Advance Payment', 'Vendor', 'VendorPayment', 'UnapplyAdvance', 'button', 7300, 7311, 'VendorPayments-UnapplyAdvance');

SET IDENTITY_INSERT Permission OFF;

-- VERIFY
SELECT PermissionType, COUNT(*) AS Cnt FROM Permission GROUP BY PermissionType ORDER BY PermissionType;
SELECT COUNT(*) AS TotalPermissions FROM Permission;
SELECT CASE WHEN COUNT(*) = 0 THEN 'OK: PermissionId = SortOrder for all rows' ELSE 'ERROR: Mismatch found!' END AS IdSortCheck
FROM Permission WHERE PermissionId != SortOrder;
