using KLS.Models;

namespace KLS.Contract.Interfaces
{
    public interface IBankFeedSourceRepository : IRepository<BankFeedSource>
    {
        /// <summary>True when Bank Feed generated the transaction on this bank row and has not reversed it.</summary>
        bool HasActiveSource(long bankFeedTransactionId);

        /// <summary>True when this vendor payment was generated by Bank Feed and is still linked.</summary>
        bool IsGeneratedVendorPayment(int vendorPaymentId);

        void ReverseVendorPayment(long bankFeedTransactionId, string? reverseReason, int empId);
    }
}
