<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5ecdbdaa-0144-44ab-a20c-6968a8fe5158</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Hubs\" />
    <Folder Include="wwwroot\Images\category\" />
    <Folder Include="wwwroot\Images\items\" />
    <Folder Include="wwwroot\Images\item\" />
    <Folder Include="wwwroot\KLS\category\" />
    <Folder Include="wwwroot\Pdf\" />
    <Folder Include="wwwroot\Python\" />
    <Folder Include="wwwroot\Payroll\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KLS.Data\KLS.Data.csproj" />
    <ProjectReference Include="..\KLS.Services\KLS.Services.csproj" />
  </ItemGroup>

</Project>
