SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================================================================
-- BankFeedSource - registration of source documents that Bank Feed itself created.
--   Plan: plan/bank-feed-create-phase-1-open-bill.md  (Slice 1)
--   Schema owner: plan/bank-feed-create.md            (Schema Plan section)
--
-- Purpose:
--   BankFeedMatch links a bank row to a journal entry that ALREADY existed.
--   BankFeedSource records the other case: Bank Feed created the source document
--   (a VendorPayment today, a CustomerPayment in Phase 2) and can therefore undo it.
--
-- QUOTED_IDENTIFIER / ANSI_NULLS above are required, not decorative: the filtered
-- unique index at the bottom cannot be created without them.
--
-- Idempotent / guarded. Safe to re-run. Rollback: BankFeedSource_create_rollback.sql
-- =============================================================================================

IF OBJECT_ID('dbo.BankFeedSource', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.BankFeedSource
    (
        BankFeedSourceId      BIGINT IDENTITY(1,1) NOT NULL,
        BankFeedTransactionId BIGINT         NOT NULL,

        -- What Bank Feed created. SourceDocId is polymorphic - it points at
        -- VendorPayment.VendorPaymentId or CustomerPayment.CustomerPaymentId
        -- depending on SourceDocType, so it deliberately has NO foreign key.
        SourceDocType         VARCHAR(50)    NOT NULL,
        SourceDocId           BIGINT         NOT NULL,

        -- The journal it posted. Audit only, and deliberately NO foreign key:
        -- reversal deletes the journal rows while keeping this row as history.
        TxId                  BIGINT         NULL,

        -- Which Bank Feed workflow produced the doc. NOT redundant with
        -- SourceDocType: Phase 5 (Expense / Check, Transfer Out) will also create
        -- a VendorPayment, so one SourceDocType will carry several Modes.
        -- No constraint pairs the two columns, for exactly that reason.
        [Mode]                VARCHAR(50)    NOT NULL,
        [Status]              VARCHAR(20)    NOT NULL,

        -- OriginalBankAmount keeps the SIGNED bank amount (negative for money out).
        -- AppliedAmount and DifferenceAmount are positive in Phase 1.
        -- DifferenceAmount = SUM(bill open balance) - SUM(applied), captured BEFORE
        -- the payment posts. No CHECK >= 0: the overpayment phase stores negatives.
        OriginalBankAmount    DECIMAL(18,2)  NOT NULL,
        AppliedAmount         DECIMAL(18,2)  NOT NULL,
        DifferenceAmount      DECIMAL(18,2)  NOT NULL,

        -- Derived by the create procedure, never supplied by the caller.
        DifferenceResolution  VARCHAR(50)    NULL,
        -- Reserved. Stays NULL in Open Bill v1: VendorPayment_Insert hardcodes the
        -- discount account to '@IDR' and takes no account parameter.
        DifferenceAccountId   INT            NULL,
        DifferenceMemo        NVARCHAR(500)  NULL,

        CreatedAt             DATETIME2      NOT NULL,
        CreatedBy             INT            NOT NULL,
        ReversedAt            DATETIME2      NULL,
        ReversedBy            INT            NULL,
        ReverseReason         NVARCHAR(500)  NULL,

        CONSTRAINT PK_BankFeedSource
            PRIMARY KEY (BankFeedSourceId),

        CONSTRAINT FK_BankFeedSource_BankFeedTx
            FOREIGN KEY (BankFeedTransactionId)
            REFERENCES dbo.BankFeedTransaction(BankFeedTransactionId),

        CONSTRAINT FK_BankFeedSource_Account
            FOREIGN KEY (DifferenceAccountId)
            REFERENCES dbo.Account(AccountId),

        CONSTRAINT CK_BankFeedSource_SourceDocType
            CHECK (SourceDocType IN ('VendorPayment', 'CustomerPayment')),

        CONSTRAINT CK_BankFeedSource_Mode
            CHECK ([Mode] IN ('PayOpenBill', 'ReceiveOpenInvoice')),

        CONSTRAINT CK_BankFeedSource_Status
            CHECK ([Status] IN ('Active', 'Reversed'))
    );
END
GO

-- Lookup by bank feed row: "did Bank Feed generate anything for this row?"
-- Drives the create-time duplicate check and the list's IsGenerated flag.
IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_BankFeedSource_BankFeedTransactionId'
                 AND object_id = OBJECT_ID('dbo.BankFeedSource'))
    CREATE NONCLUSTERED INDEX IX_BankFeedSource_BankFeedTransactionId
        ON dbo.BankFeedSource(BankFeedTransactionId)
        INCLUDE ([Status]);
GO

-- Reverse lookup: "was this payment generated by Bank Feed?"
-- Used by the Vendor Payments delete guard (master Hole 2).
IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_BankFeedSource_Doc'
                 AND object_id = OBJECT_ID('dbo.BankFeedSource'))
    CREATE NONCLUSTERED INDEX IX_BankFeedSource_Doc
        ON dbo.BankFeedSource(SourceDocType, SourceDocId)
        INCLUDE ([Status]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'IX_BankFeedSource_TxId'
                 AND object_id = OBJECT_ID('dbo.BankFeedSource'))
    CREATE NONCLUSTERED INDEX IX_BankFeedSource_TxId
        ON dbo.BankFeedSource(TxId);
GO

-- One source document can only be actively registered once. Reversed rows are
-- excluded so history accumulates freely.
-- Note this does NOT limit a bank feed row to one active source - that stays a
-- service-level rule in v1, because grouped ACH/batch cases may need several.
IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'UX_BankFeedSource_ActiveDoc'
                 AND object_id = OBJECT_ID('dbo.BankFeedSource'))
    CREATE UNIQUE NONCLUSTERED INDEX UX_BankFeedSource_ActiveDoc
        ON dbo.BankFeedSource(SourceDocType, SourceDocId)
        WHERE [Status] = 'Active';
GO
