SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF DB_NAME() NOT IN ('KLS_2026', 'GUS_2026')
BEGIN
    THROW 51000, 'Wrong database for SALES_TRANSIT_UPDATE_DOCUMENT_ACTION rollback.', 1;
END
GO

DELETE FROM dbo.SystemSetting
WHERE SettingKey = 'SALES_TRANSIT_UPDATE_DOCUMENT_ACTION';
GO
