IF COL_LENGTH('dbo.Payee', 'Phone1') IS NOT NULL
BEGIN
    ALTER TABLE dbo.Payee ALTER COLUMN Phone1 NVARCHAR(80) NULL;
    ALTER TABLE dbo.Payee ALTER COLUMN Phone2 NVARCHAR(80) NULL;
    ALTER TABLE dbo.Payee ALTER COLUMN Phone3 NVARCHAR(80) NULL;
    ALTER TABLE dbo.Payee ALTER COLUMN Phone4 NVARCHAR(80) NULL;
    ALTER TABLE dbo.Payee ALTER COLUMN Phone5 NVARCHAR(80) NULL;
    ALTER TABLE dbo.Payee ALTER COLUMN Phone6 NVARCHAR(80) NULL;
END;

