IF COL_LENGTH('dbo.Shipment', 'ETD') IS NULL
BEGIN
    ALTER TABLE dbo.Shipment
        ADD ETD DATE NULL;
END
GO

IF COL_LENGTH('dbo.Shipment', 'DutyStatus') IS NULL
BEGIN
    ALTER TABLE dbo.Shipment
        ADD DutyStatus NVARCHAR(50) NULL;
END
GO

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
  AND TABLE_NAME = 'Shipment'
  AND COLUMN_NAME IN ('ETD', 'DutyStatus')
ORDER BY COLUMN_NAME;
GO
