SET XACT_ABORT ON;

BEGIN TRANSACTION;

IF OBJECT_ID('dbo.Country', 'U') IS NULL OR COL_LENGTH('dbo.Country', 'ISOAlpha2') IS NULL
BEGIN
    THROW 50010, 'Canonical dbo.Country table is not present. Run Country_Master_2B_schema.sql first.', 1;
END;

MERGE dbo.Country AS tgt
USING (VALUES
    ('AFG', N'Afghanistan', 'AF', 'AFG', NULL, NULL, NULL, 1, 10),
    ('ALB', N'Albania', 'AL', 'ALB', NULL, NULL, NULL, 1, 20),
    ('DZA', N'Algeria', 'DZ', 'DZA', NULL, NULL, NULL, 1, 30),
    ('AND', N'Andorra', 'AD', 'AND', NULL, NULL, NULL, 1, 40),
    ('AGO', N'Angola', 'AO', 'AGO', NULL, NULL, NULL, 1, 50),
    ('ATG', N'Antigua and Barbuda', 'AG', 'ATG', NULL, NULL, NULL, 1, 60),
    ('ARG', N'Argentina', 'AR', 'ARG', NULL, NULL, NULL, 1, 70),
    ('ARM', N'Armenia', 'AM', 'ARM', NULL, NULL, NULL, 1, 80),
    ('AUS', N'Australia', 'AU', 'AUS', NULL, NULL, NULL, 1, 90),
    ('AUT', N'Austria', 'AT', 'AUT', NULL, NULL, NULL, 1, 100),
    ('AZE', N'Azerbaijan', 'AZ', 'AZE', NULL, NULL, NULL, 1, 110),
    ('BHS', N'Bahamas', 'BS', 'BHS', NULL, NULL, NULL, 1, 120),
    ('BHR', N'Bahrain', 'BH', 'BHR', NULL, NULL, NULL, 1, 130),
    ('BGD', N'Bangladesh', 'BD', 'BGD', NULL, NULL, NULL, 1, 140),
    ('BRB', N'Barbados', 'BB', 'BRB', NULL, NULL, NULL, 1, 150),
    ('BLR', N'Belarus', 'BY', 'BLR', NULL, NULL, NULL, 1, 160),
    ('BEL', N'Belgium', 'BE', 'BEL', NULL, NULL, NULL, 1, 170),
    ('BLZ', N'Belize', 'BZ', 'BLZ', NULL, NULL, NULL, 1, 180),
    ('BEN', N'Benin', 'BJ', 'BEN', NULL, NULL, NULL, 1, 190),
    ('BTN', N'Bhutan', 'BT', 'BTN', NULL, NULL, NULL, 1, 200),
    ('BOL', N'Bolivia', 'BO', 'BOL', NULL, NULL, NULL, 1, 210),
    ('BIH', N'Bosnia and Herzegovina', 'BA', 'BIH', NULL, NULL, NULL, 1, 220),
    ('BWA', N'Botswana', 'BW', 'BWA', NULL, NULL, NULL, 1, 230),
    ('BRA', N'Brazil', 'BR', 'BRA', NULL, NULL, NULL, 1, 240),
    ('BRN', N'Brunei', 'BN', 'BRN', NULL, NULL, NULL, 1, 250),
    ('BGR', N'Bulgaria', 'BG', 'BGR', NULL, NULL, NULL, 1, 260),
    ('BFA', N'Burkina Faso', 'BF', 'BFA', NULL, NULL, NULL, 1, 270),
    ('BDI', N'Burundi', 'BI', 'BDI', NULL, NULL, NULL, 1, 280),
    ('CPV', N'Cabo Verde', 'CV', 'CPV', NULL, NULL, NULL, 1, 290),
    ('KHM', N'Cambodia', 'KH', 'KHM', NULL, NULL, NULL, 1, 300),
    ('CMR', N'Cameroon', 'CM', 'CMR', NULL, NULL, NULL, 1, 310),
    ('CAN', N'Canada', 'CA', 'CAN', NULL, NULL, NULL, 1, 320),
    ('CAF', N'Central African Republic', 'CF', 'CAF', NULL, NULL, NULL, 1, 330),
    ('TCD', N'Chad', 'TD', 'TCD', NULL, NULL, NULL, 1, 340),
    ('CHL', N'Chile', 'CL', 'CHL', NULL, NULL, NULL, 1, 350),
    ('CHN', N'China', 'CN', 'CHN', NULL, NULL, NULL, 1, 360),
    ('COL', N'Colombia', 'CO', 'COL', NULL, NULL, NULL, 1, 370),
    ('COM', N'Comoros', 'KM', 'COM', NULL, NULL, NULL, 1, 380),
    ('COG', N'Congo', 'CG', 'COG', NULL, NULL, NULL, 1, 390),
    ('COD', N'Congo (Democratic Republic)', 'CD', 'COD', NULL, NULL, NULL, 1, 400),
    ('CRI', N'Costa Rica', 'CR', 'CRI', NULL, NULL, NULL, 1, 410),
    ('CIV', N'Côte d''Ivoire', 'CI', 'CIV', NULL, NULL, NULL, 1, 420),
    ('HRV', N'Croatia', 'HR', 'HRV', NULL, NULL, NULL, 1, 430),
    ('CUB', N'Cuba', 'CU', 'CUB', NULL, NULL, NULL, 1, 440),
    ('CYP', N'Cyprus', 'CY', 'CYP', NULL, NULL, NULL, 1, 450),
    ('CZE', N'Czech Republic', 'CZ', 'CZE', NULL, NULL, NULL, 1, 460),
    ('DNK', N'Denmark', 'DK', 'DNK', NULL, NULL, NULL, 1, 470),
    ('DJI', N'Djibouti', 'DJ', 'DJI', NULL, NULL, NULL, 1, 480),
    ('DMA', N'Dominica', 'DM', 'DMA', NULL, NULL, NULL, 1, 490),
    ('DOM', N'Dominican Republic', 'DO', 'DOM', NULL, NULL, NULL, 1, 500),
    ('ECU', N'Ecuador', 'EC', 'ECU', NULL, NULL, NULL, 1, 510),
    ('EGY', N'Egypt', 'EG', 'EGY', NULL, NULL, NULL, 1, 520),
    ('SLV', N'El Salvador', 'SV', 'SLV', NULL, NULL, NULL, 1, 530),
    ('GNQ', N'Equatorial Guinea', 'GQ', 'GNQ', NULL, NULL, NULL, 1, 540),
    ('ERI', N'Eritrea', 'ER', 'ERI', NULL, NULL, NULL, 1, 550),
    ('EST', N'Estonia', 'EE', 'EST', NULL, NULL, NULL, 1, 560),
    ('SWZ', N'Eswatini', 'SZ', 'SWZ', NULL, NULL, NULL, 1, 570),
    ('ETH', N'Ethiopia', 'ET', 'ETH', NULL, NULL, NULL, 1, 580),
    ('FJI', N'Fiji', 'FJ', 'FJI', NULL, NULL, NULL, 1, 590),
    ('FIN', N'Finland', 'FI', 'FIN', NULL, NULL, NULL, 1, 600),
    ('FRA', N'France', 'FR', 'FRA', NULL, NULL, NULL, 1, 610),
    ('GAB', N'Gabon', 'GA', 'GAB', NULL, NULL, NULL, 1, 620),
    ('GMB', N'Gambia', 'GM', 'GMB', NULL, NULL, NULL, 1, 630),
    ('GEO', N'Georgia', 'GE', 'GEO', NULL, NULL, NULL, 1, 640),
    ('DEU', N'Germany', 'DE', 'DEU', NULL, NULL, NULL, 1, 650),
    ('GHA', N'Ghana', 'GH', 'GHA', NULL, NULL, NULL, 1, 660),
    ('GRC', N'Greece', 'GR', 'GRC', NULL, NULL, NULL, 1, 670),
    ('GRD', N'Grenada', 'GD', 'GRD', NULL, NULL, NULL, 1, 680),
    ('GTM', N'Guatemala', 'GT', 'GTM', NULL, NULL, NULL, 1, 690),
    ('GIN', N'Guinea', 'GN', 'GIN', NULL, NULL, NULL, 1, 700),
    ('GNB', N'Guinea-Bissau', 'GW', 'GNB', NULL, NULL, NULL, 1, 710),
    ('GUY', N'Guyana', 'GY', 'GUY', NULL, NULL, NULL, 1, 720),
    ('HTI', N'Haiti', 'HT', 'HTI', NULL, NULL, NULL, 1, 730),
    ('HND', N'Honduras', 'HN', 'HND', NULL, NULL, NULL, 1, 740),
    ('HUN', N'Hungary', 'HU', 'HUN', NULL, NULL, NULL, 1, 750),
    ('ISL', N'Iceland', 'IS', 'ISL', NULL, NULL, NULL, 1, 760),
    ('IND', N'India', 'IN', 'IND', NULL, NULL, NULL, 1, 770),
    ('IDN', N'Indonesia', 'ID', 'IDN', NULL, NULL, NULL, 1, 780),
    ('IRN', N'Iran', 'IR', 'IRN', NULL, NULL, NULL, 1, 790),
    ('IRQ', N'Iraq', 'IQ', 'IRQ', NULL, NULL, NULL, 1, 800),
    ('IRL', N'Ireland', 'IE', 'IRL', NULL, NULL, NULL, 1, 810),
    ('ISR', N'Israel', 'IL', 'ISR', NULL, NULL, NULL, 1, 820),
    ('ITA', N'Italy', 'IT', 'ITA', NULL, NULL, NULL, 1, 830),
    ('JAM', N'Jamaica', 'JM', 'JAM', NULL, NULL, NULL, 1, 840),
    ('JPN', N'Japan', 'JP', 'JPN', NULL, NULL, NULL, 1, 850),
    ('JOR', N'Jordan', 'JO', 'JOR', NULL, NULL, NULL, 1, 860),
    ('KAZ', N'Kazakhstan', 'KZ', 'KAZ', NULL, NULL, NULL, 1, 870),
    ('KEN', N'Kenya', 'KE', 'KEN', NULL, NULL, NULL, 1, 880),
    ('KIR', N'Kiribati', 'KI', 'KIR', NULL, NULL, NULL, 1, 890),
    ('KWT', N'Kuwait', 'KW', 'KWT', NULL, NULL, NULL, 1, 900),
    ('KGZ', N'Kyrgyzstan', 'KG', 'KGZ', NULL, NULL, NULL, 1, 910),
    ('LAO', N'Laos', 'LA', 'LAO', NULL, NULL, NULL, 1, 920),
    ('LVA', N'Latvia', 'LV', 'LVA', NULL, NULL, NULL, 1, 930),
    ('LBN', N'Lebanon', 'LB', 'LBN', NULL, NULL, NULL, 1, 940),
    ('LSO', N'Lesotho', 'LS', 'LSO', NULL, NULL, NULL, 1, 950),
    ('LBR', N'Liberia', 'LR', 'LBR', NULL, NULL, NULL, 1, 960),
    ('LBY', N'Libya', 'LY', 'LBY', NULL, NULL, NULL, 1, 970),
    ('LIE', N'Liechtenstein', 'LI', 'LIE', NULL, NULL, NULL, 1, 980),
    ('LTU', N'Lithuania', 'LT', 'LTU', NULL, NULL, NULL, 1, 990),
    ('LUX', N'Luxembourg', 'LU', 'LUX', NULL, NULL, NULL, 1, 1000),
    ('MDG', N'Madagascar', 'MG', 'MDG', NULL, NULL, NULL, 1, 1010),
    ('MWI', N'Malawi', 'MW', 'MWI', NULL, NULL, NULL, 1, 1020),
    ('MYS', N'Malaysia', 'MY', 'MYS', NULL, NULL, NULL, 1, 1030),
    ('MDV', N'Maldives', 'MV', 'MDV', NULL, NULL, NULL, 1, 1040),
    ('MLI', N'Mali', 'ML', 'MLI', NULL, NULL, NULL, 1, 1050),
    ('MLT', N'Malta', 'MT', 'MLT', NULL, NULL, NULL, 1, 1060),
    ('MHL', N'Marshall Islands', 'MH', 'MHL', NULL, NULL, NULL, 1, 1070),
    ('MRT', N'Mauritania', 'MR', 'MRT', NULL, NULL, NULL, 1, 1080),
    ('MUS', N'Mauritius', 'MU', 'MUS', NULL, NULL, NULL, 1, 1090),
    ('MEX', N'Mexico', 'MX', 'MEX', NULL, NULL, NULL, 1, 1100),
    ('FSM', N'Micronesia', 'FM', 'FSM', NULL, NULL, NULL, 1, 1110),
    ('MDA', N'Moldova', 'MD', 'MDA', NULL, NULL, NULL, 1, 1120),
    ('MCO', N'Monaco', 'MC', 'MCO', NULL, NULL, NULL, 1, 1130),
    ('MNG', N'Mongolia', 'MN', 'MNG', NULL, NULL, NULL, 1, 1140),
    ('MNE', N'Montenegro', 'ME', 'MNE', NULL, NULL, NULL, 1, 1150),
    ('MAR', N'Morocco', 'MA', 'MAR', NULL, NULL, NULL, 1, 1160),
    ('MOZ', N'Mozambique', 'MZ', 'MOZ', NULL, NULL, NULL, 1, 1170),
    ('MMR', N'Myanmar', 'MM', 'MMR', NULL, NULL, NULL, 1, 1180),
    ('NAM', N'Namibia', 'NA', 'NAM', NULL, NULL, NULL, 1, 1190),
    ('NRU', N'Nauru', 'NR', 'NRU', NULL, NULL, NULL, 1, 1200),
    ('NPL', N'Nepal', 'NP', 'NPL', NULL, NULL, NULL, 1, 1210),
    ('NLD', N'Netherlands', 'NL', 'NLD', NULL, NULL, NULL, 1, 1220),
    ('NZL', N'New Zealand', 'NZ', 'NZL', NULL, NULL, NULL, 1, 1230),
    ('NIC', N'Nicaragua', 'NI', 'NIC', NULL, NULL, NULL, 1, 1240),
    ('NER', N'Niger', 'NE', 'NER', NULL, NULL, NULL, 1, 1250),
    ('NGA', N'Nigeria', 'NG', 'NGA', NULL, NULL, NULL, 1, 1260),
    ('PRK', N'North Korea', 'KP', 'PRK', NULL, NULL, NULL, 1, 1270),
    ('MKD', N'North Macedonia', 'MK', 'MKD', NULL, NULL, NULL, 1, 1280),
    ('NOR', N'Norway', 'NO', 'NOR', NULL, NULL, NULL, 1, 1290),
    ('OMN', N'Oman', 'OM', 'OMN', NULL, NULL, NULL, 1, 1300),
    ('PAK', N'Pakistan', 'PK', 'PAK', NULL, NULL, NULL, 1, 1310),
    ('PLW', N'Palau', 'PW', 'PLW', NULL, NULL, NULL, 1, 1320),
    ('PAN', N'Panama', 'PA', 'PAN', NULL, NULL, NULL, 1, 1330),
    ('PNG', N'Papua New Guinea', 'PG', 'PNG', NULL, NULL, NULL, 1, 1340),
    ('PRY', N'Paraguay', 'PY', 'PRY', NULL, NULL, NULL, 1, 1350),
    ('PER', N'Peru', 'PE', 'PER', NULL, NULL, NULL, 1, 1360),
    ('PHL', N'Philippines', 'PH', 'PHL', NULL, NULL, NULL, 1, 1370),
    ('POL', N'Poland', 'PL', 'POL', NULL, NULL, NULL, 1, 1380),
    ('PRT', N'Portugal', 'PT', 'PRT', NULL, NULL, NULL, 1, 1390),
    ('QAT', N'Qatar', 'QA', 'QAT', NULL, NULL, NULL, 1, 1400),
    ('ROU', N'Romania', 'RO', 'ROU', NULL, NULL, NULL, 1, 1410),
    ('RUS', N'Russia', 'RU', 'RUS', NULL, NULL, NULL, 1, 1420),
    ('RWA', N'Rwanda', 'RW', 'RWA', NULL, NULL, NULL, 1, 1430),
    ('KNA', N'Saint Kitts and Nevis', 'KN', 'KNA', NULL, NULL, NULL, 1, 1440),
    ('LCA', N'Saint Lucia', 'LC', 'LCA', NULL, NULL, NULL, 1, 1450),
    ('VCT', N'Saint Vincent and the Grenadines', 'VC', 'VCT', NULL, NULL, NULL, 1, 1460),
    ('WSM', N'Samoa', 'WS', 'WSM', NULL, NULL, NULL, 1, 1470),
    ('SMR', N'San Marino', 'SM', 'SMR', NULL, NULL, NULL, 1, 1480),
    ('STP', N'Sao Tome and Principe', 'ST', 'STP', NULL, NULL, NULL, 1, 1490),
    ('SAU', N'Saudi Arabia', 'SA', 'SAU', NULL, NULL, NULL, 1, 1500),
    ('SEN', N'Senegal', 'SN', 'SEN', NULL, NULL, NULL, 1, 1510),
    ('SRB', N'Serbia', 'RS', 'SRB', NULL, NULL, NULL, 1, 1520),
    ('SYC', N'Seychelles', 'SC', 'SYC', NULL, NULL, NULL, 1, 1530),
    ('SLE', N'Sierra Leone', 'SL', 'SLE', NULL, NULL, NULL, 1, 1540),
    ('SGP', N'Singapore', 'SG', 'SGP', NULL, NULL, NULL, 1, 1550),
    ('SVK', N'Slovakia', 'SK', 'SVK', NULL, NULL, NULL, 1, 1560),
    ('SVN', N'Slovenia', 'SI', 'SVN', NULL, NULL, NULL, 1, 1570),
    ('SLB', N'Solomon Islands', 'SB', 'SLB', NULL, NULL, NULL, 1, 1580),
    ('SOM', N'Somalia', 'SO', 'SOM', NULL, NULL, NULL, 1, 1590),
    ('ZAF', N'South Africa', 'ZA', 'ZAF', NULL, NULL, NULL, 1, 1600),
    ('KOR', N'South Korea', 'KR', 'KOR', NULL, NULL, NULL, 1, 1610),
    ('SSD', N'South Sudan', 'SS', 'SSD', NULL, NULL, NULL, 1, 1620),
    ('ESP', N'Spain', 'ES', 'ESP', NULL, NULL, NULL, 1, 1630),
    ('LKA', N'Sri Lanka', 'LK', 'LKA', NULL, NULL, NULL, 1, 1640),
    ('SDN', N'Sudan', 'SD', 'SDN', NULL, NULL, NULL, 1, 1650),
    ('SUR', N'Suriname', 'SR', 'SUR', NULL, NULL, NULL, 1, 1660),
    ('SWE', N'Sweden', 'SE', 'SWE', NULL, NULL, NULL, 1, 1670),
    ('CHE', N'Switzerland', 'CH', 'CHE', NULL, NULL, NULL, 1, 1680),
    ('SYR', N'Syria', 'SY', 'SYR', NULL, NULL, NULL, 1, 1690),
    ('TJK', N'Tajikistan', 'TJ', 'TJK', NULL, NULL, NULL, 1, 1700),
    ('TZA', N'Tanzania', 'TZ', 'TZA', NULL, NULL, NULL, 1, 1710),
    ('THA', N'Thailand', 'TH', 'THA', NULL, NULL, NULL, 1, 1720),
    ('TLS', N'Timor-Leste', 'TL', 'TLS', NULL, NULL, NULL, 1, 1730),
    ('TGO', N'Togo', 'TG', 'TGO', NULL, NULL, NULL, 1, 1740),
    ('TON', N'Tonga', 'TO', 'TON', NULL, NULL, NULL, 1, 1750),
    ('TTO', N'Trinidad and Tobago', 'TT', 'TTO', NULL, NULL, NULL, 1, 1760),
    ('TUN', N'Tunisia', 'TN', 'TUN', NULL, NULL, NULL, 1, 1770),
    ('TUR', N'Turkey', 'TR', 'TUR', NULL, NULL, NULL, 1, 1780),
    ('TKM', N'Turkmenistan', 'TM', 'TKM', NULL, NULL, NULL, 1, 1790),
    ('TUV', N'Tuvalu', 'TV', 'TUV', NULL, NULL, NULL, 1, 1800),
    ('UGA', N'Uganda', 'UG', 'UGA', NULL, NULL, NULL, 1, 1810),
    ('UKR', N'Ukraine', 'UA', 'UKR', NULL, NULL, NULL, 1, 1820),
    ('ARE', N'United Arab Emirates', 'AE', 'ARE', NULL, NULL, NULL, 1, 1830),
    ('GBR', N'United Kingdom', 'GB', 'GBR', NULL, NULL, NULL, 1, 1840),
    ('USA', N'United States', 'US', 'USA', NULL, NULL, NULL, 1, 1850),
    ('URY', N'Uruguay', 'UY', 'URY', NULL, NULL, NULL, 1, 1860),
    ('UZB', N'Uzbekistan', 'UZ', 'UZB', NULL, NULL, NULL, 1, 1870),
    ('VUT', N'Vanuatu', 'VU', 'VUT', NULL, NULL, NULL, 1, 1880),
    ('VAT', N'Vatican City', 'VA', 'VAT', NULL, NULL, NULL, 1, 1890),
    ('VEN', N'Venezuela', 'VE', 'VEN', NULL, NULL, NULL, 1, 1900),
    ('VNM', N'Vietnam', 'VN', 'VNM', NULL, NULL, NULL, 1, 1910),
    ('YEM', N'Yemen', 'YE', 'YEM', NULL, NULL, NULL, 1, 1920),
    ('ZMB', N'Zambia', 'ZM', 'ZMB', NULL, NULL, NULL, 1, 1930),
    ('ZWE', N'Zimbabwe', 'ZW', 'ZWE', NULL, NULL, NULL, 1, 1940)
) AS src (CountryCode, CountryName, ISOAlpha2, ISOAlpha3, NumericCode, CallingCode, Continent, IsActive, SortOrder)
ON tgt.ISOAlpha2 = src.ISOAlpha2
WHEN MATCHED THEN
    UPDATE SET
        CountryCode = src.CountryCode,
        CountryName = src.CountryName,
        ISOAlpha3 = src.ISOAlpha3,
        NumericCode = src.NumericCode,
        CallingCode = src.CallingCode,
        Continent = src.Continent,
        IsActive = src.IsActive,
        SortOrder = src.SortOrder,
        UpdatedAt = SYSUTCDATETIME()
WHEN NOT MATCHED BY TARGET THEN
    INSERT (CountryCode, CountryName, ISOAlpha2, ISOAlpha3, NumericCode, CallingCode, Continent, IsActive, SortOrder)
    VALUES (src.CountryCode, src.CountryName, src.ISOAlpha2, src.ISOAlpha3, src.NumericCode, src.CallingCode, src.Continent, src.IsActive, src.SortOrder);

COMMIT TRANSACTION;